uwsgi --plugin=python3 \
    --chdir=/home/painkiller/Desktop/startupclub/startup_club_site \
    --wsgi-file=/home/painkiller/Desktop/startupclub/startup_club_site/club_site/club_site/wsgi.py \
    --env DJANGO_SETTINGS_MODULE=club_site.settings \
    --master --pidfile=/tmp/project-master.pid \
    --socket=127.0.0.1:8000 \      # can also be a file
    --processes=5 \                 # number of worker processes
    --uid=1000 --gid=2000 \         # if root, uwsgi can drop privileges
    --harakiri=20 \                 # respawn processes taking more than 20 seconds
    --max-requests=5000 \           # respawn processes after serving 5000 requests
    --vacuum \                      # clear environment on exit
    --home=/home/painkiller/Desktop/startupclub/startup_club_site/env \   # optional path to a virtualenv
    --daemonize=/var/log/uwsgi/yourproject.log      # background the process
