# Generated by Django 3.0.3 on 2020-03-20 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='new', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('idea', 'Идея'), ('development', 'Разработка прототипа'), ('scale', 'Маштабирование')], default='idea', max_length=25)),
                ('founder', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
