# Generated by Django 3.0.3 on 2020-03-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='founder',
            new_name='founders',
        ),
    ]
