# Generated by Django 3.0.3 on 2020-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200320_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Идея', 'Идея'), ('Разработка прототипа', 'Разработка прототипа'), ('Маштабирование', 'Маштабирование')], default='idea', max_length=25),
        ),
    ]
