# Generated by Django 3.0.3 on 2020-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200321_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preza',
            field=models.FileField(blank=True, upload_to='projects/%Y/%m/'),
        ),
    ]
