# Generated by Django 3.0.3 on 2020-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_preza'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_pitch',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Идея', 'Идея'), ('Разработка прототипа', 'Разработка прототипа'), ('Маштабирование', 'Маштабирование')], default='Идея', max_length=25),
        ),
    ]
