# Generated by Django 3.0.3 on 2020-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200324_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='can_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('index', 'index'), ('useful', 'useful'), ('news', 'news')], default='news', max_length=25),
        ),
    ]
